### ISSUE TITLE
License inconsistency

### ISSUE THREAD

**Issue by smahs** [jakubknejzlik/ts-query#5]
The README.md says that the library is covered under the MIT license, but the github metadata says it's under the GPL3 license. Since these are incompatible license, suggest changing one of these to be consistent.

PS it's nicely designed API. Thanks for the effort.

**Comment by jakubknejzlik** [comment]
Hi, thanks for letting me know, I've updated the license to MIT.

PS: thanks for the feedback, let me know if You are missing anything or have any idea how to improve it as I'm currently building a lot of stuff and any ideas are really welcome.
